class Liste {
  List Norse = [
    "Başlangıçta boşluk vardı (Ginnungagap). Dünya daha var olmadan önce 11 nehir akan Niflheim'da ölüm var oldu.",
    "Niflheim'ın güneyinde başka bir sıcak dünya daha oluştu; Muspell; Devlerin koruduğu yer. Devler buraya Stur yani Siyah dediler. Niflheim'ın nehirleri donmuştu. Bu nehirlere Ginnungagap dendi. Günün birinde Muspell'deki kıvılcımlar nehirlerin üzerine düştü ve nehirleri eritti.",
    "Erimiş nehirlerden oluşan damlacıklar Ymir'i şekillendirdi ve Ymir'in terinden diğer dişi ve erkek devler oluştu Yaratılış efsanesinin bir başka versiyonu daha vardır.",
    "Eriyen damlalar en ilkel inek şeklini aldılar. Audhumla; sütüyle Ymir'i besleyen inek. Audhumla aynı zamanda tuz parçalarını yalayarak bu bloklara ilk insan şeklini verir.",
    "İlk insan Buri. Buri'nin, bir devin kızı olan Bolthor ile evli bir oğlu vardır; Borr. Bolthor'u Odin, Vili ve Ve birleşerek Borr'a uygun bir biçimde yarattılar. Ve şeklinden dolayı Ymir'i öldürdüler. Odin ve kardeşleri öldürdükleri Ymir’in vücudunun parçalarıyla dünyayı oluştururlar. Ardından Tanrılar Midgard adlı orta diyarı yaratırlar ve orada yaşayacak ilk insanları bir Dişbudak ağacı bir de Karaağaçtan var ederler.",
    "Bu ağaçlara Odin hayat üfler, Vili, duygu ve düşünce verir. Ve ise ağaçlara görme ve duyma yeteneği kazandırır.Düşünen, nefes alan, duyan ve de görebilen iki ağaç. Bu ağaçlar insan ırkının ilk modelleriydi. Erkeğe Askr (dişbudak), dişiye de Embla (karaağaç) dediler.",
    "Ardından Asgard'ı yarattılar. Tanrıların meskenini. Snorri diğer birçok versiyonda kader ağacı Ygdrassil'den bahseder. Onun ne kadar ihtişamlı olduğunu, dünyanın merkezinde nasıl görkemli bir şekilde yükseldiğini tasvir eder. Ağacın altındaki kader feminen formu olarak tasvir edilir ve insan hayatının buradan başladığı düşünülür.",
    "Bazı versiyonlarda da Tanrıların büyük meclisinin burada toplanıp kararlar aldığından bahsedilir. Bu ağaç üç köklüdür; Bu köklerden biri cehenneme kadar uzanır, diğeri devler ülkesine gider ve sonuncu kök de insanların dünyasına gider. Bütün dünyanın mutluluğu bu ilk ağaca bağlıydı. İskandinav tanrıları iki grupta toplanır; Aesir ve Vanir tanrıları.",
    "Aesir'in en önemli tanrıları; Odin, Thor ve bazen de Tyr, Vanir'deki önemli tanrılar ise Njord, Frey ve Freya'dır. Vanir; Zenginlik, verimlilik ve doğurganlığı simgeler. Vanir doğurganlığı sembolize eden toprak ve denizle sembolleştirilmiştir. Aesir; Diğer bütün değerlerle sembolleştirilmiştir. Odin bir büyücüdür, tanrıların şefidir ve tüm kahramanların başıdır.",
    "Thor, çekicin tanrısıdır ve havaya hükmeder. Birçok öyküde bu ikili barış içinde yaşarlar ve birbirlerine yardım ederler. En önemli mitolojik hikâyeler uzak geçmişte bir zamanda, Vanir ve Aesir arasında çok vahşi bir savaşın çıktığından bahseder.",
    "Bazı bilginler bu savaşın Cermen ırkının diğer ırklarla karşılaşmasının bir yansıması olarak görürler. Georges Dumezil ve Jan De Vries, tanrılar arasındaki savaş ve bölünmenin Hint-Avrupa mitolojisinin bir parçası olduğunu ortaya çıkardılar.Bilinen üçlü; sihirsel güçleri adilce kullanan Odin ve Thor tarafından yaratılmıştı. Tyr savaş tanrısı ve Vanir bolluk tanrısı beraberce hiyerarşiyi bozguna uğratmışlardı. İskandinav mitolojisinde Odin ve Thor arasındaki çelişki, bütün tanrılık statülerinin Vanir'de kalmasıyla başladı. Aesir'e bir kadın olan Gullveig'i (Altın sarhoşu) göndererek yalvardılar.",
    "Daha sonra da savaş çıktı. Her iki tarafta tükendikten sonra, iki taraf kendi grup üyelerini değiş tokuş etti. Vanir Njord ve oğlu Frey'i ,Aesir ise Mimir ve Hoenir'i verdi. Bu geçici barış tüm tanrıların toplanarak Kvasir'i yaratmalarıyla kutlandı. Kvasir barış ve mutluluğun sembolü daha sonra kurban edildi. Ve kanından tanrılar için bir içki yaratıldı. Böylece Kvasir Tanrıları sarhoş eden ve ozanlara ilham veren bir içecek olmuştu.",
    "Önemli bir başka mitolojik efsane de Balder ve Loki'yi anlatır. Odin'in oğullarından Balder burada akıl, sevgi ve bilginin tanrısı olarak karşımıza çıkar. Cennette Glitnir denilen bir yeri korumaktadır. Her türlü anlaşmazlıkta bütün tanrılar onun adaletine güvendiklerinden ona gelirler ve burada Balder'in adaleti sağlaması beklenir.Ve Balder adaleti yerine getirir.",
    "Loki Aesir tarafından evlat edinilmiş bir devdir. Loki ve Odin aralarında bir dostluk antlaşması yapmışlardı. Bir gece Balder kendi ölümü hakkında çok rahatsız edici bir rüya görür. Annesi Frigg, su, ateş, doğadaki bütün elementlere, kuşlara, canavarlara, toprak ve taşlara, Balder'a zarar vermemeleri için yemin ettirir. Böylece Balder Ölümsüz olur. Bundan sonra Aesir Balder'ı ortalarına alıp onunla eğlenmeye başlar. Ona küçük ok, taş vs. şeyler atarlar. Bu yeminden dolayı Balder sadakatsizliklle karşı karşıya kalmıştır. Loki bu dramayı görünce merak eder ve kadın kılığında Frigg'in yanına giderek ona neler olduğunu sorar. Frigg de ona yeminden bahseder ve yeminin içine katılmayan tek şeyin ökse otu olduğunu da sözlerine ekler. Bunu duyan Loki hemen Aesir'e sunulmak üzere ökse otu getirir. Bunu kör tanrı Hoder'e kendi isteği ile verecek ve böylelikle Balder'a acı çektirme oyununa o da katılabilecektir. Balder'a ökse otundan yapılmış ok atılır ve Balder ölür.",
    "Aesir bu olayın suçlusundan intikam almak ister ama bulundukları yerin kutsallığından dolayı bunu yapamazlar. Balder Hel'e gidecektir, yani tüm ölülerin gittiği yere çünkü o bir savaşçı değil ve bir savaşta ölmemiştir dolayısıyla da kahramanların yeri olan Valhalla'ya gidemez.",
    "Balder Hel'den ancak Odin onun çıkmasına izin verdiğinde ve aynı zamanda yaşayan ve ölü olan her canlının onun için gözyaşı döktüğü zaman çıkabilecektir. Aksi takdirde sonsuza dek orada kalmaya mahkûm olacaktır. Bu kehanet üzerine Aesir bütün dünyaya elçiler yollar. Doğaya, insanlığa, tanrılara ve onlara Balder için gözyaşı dökmelerini emreder. Bunu tüm yaşayanlar kabul eder. Tabii ki Devlerin kraliçesi Thork (kılık değiştirmiş Loki) hariç. Ve ağlamamak için de kesin kararlıdır. Aesir Thork'un Loki olduğunu fark ettiğinde, onun bu şeytanca oyunlarına son vermesi için zincire vurur.",
    "Kehanete göre Loki bir gün bir şekilde zincirlerini kıracak ve bu bütün şeytanların canavarların ve devlerin tanrılara karşı olan büyük savaş Ragnarok'ta kaybedeceğinin işareti olacaktır. Ragnarok'ta Odin kurt Fenrir tarafından yenilir. Daha sonra da Fenrir Odin'in oğlu Vidar tarafından öldürülür. Bu olaydan sonra tanrılar arasındaki korkunç savaşlar başlar. Tanrı Heimdall ve Loki karşı karşıya gelip birbirlerini öldürene kadar savaşırlar. Ve daha sonra Dünya bir ateşle yok edilir. Evren denizin dibine batmaya başlar. Bu son tekrar doğuşla kendini devam etirir. Dünya denizden tekrar yükselir, yeşillenir, bitkilerle dolup taşar. Aesir'in ölü oğulları Asgard'a geri döner ve atalarının yolunu izlerler."
  ];
  List Greek = [
    "Yunan mitolojisine göre başlangıçta Khaos vardı. Yunanca anlamı açık ya da boşluk olan Khaos, Hesiodos'a göre sonsuz bir boşluk.Bu boşluktan ilkin Gaia doğar",
    "sonrasında Ölüler Ülkesi'nin en derin yeri Tartaraos",
    "daha sonra Eros,",
    "sonra yeraltı karanlığını simgeleyen Erebos",
    "ve yeryüzü karanlığını simgeleyen Nyks(Gece) doğar.",
    "Erebos ve Nyks birleşerek Aither’i (Esîr), yani dünyayı saran hava tabakasının üstündeki arı ve ışıklı Gök’ü ve Hemera’yı (Gün) meydana getirdiler.",
    "Toprak Ana tek başına Uranos’u (Gök), Pontos’u (Deniz) ve Dağlar’ı yarattı. Peşinden, oğulları Uranos ve Pontos’ta birleşerek, artık yaratılmış olan evreni tanrısal varlıklarla doldurdu.",
    "Gaia’nın Uranos’la birleşmesinden, altısı erkek altısı dişi olmak üzere on iki tane Titan, üç Kyklop, üç tane de Hekatonkheir (Yüz Kollu) doğdu. Okeanos, Koios, Krios, Hyperion, İapetos ve Kronos erkek Titan’lardı. Titanides denilen dişi Titanlar ise şunlardı: Theia, Rheia, Themis, Phoibe, Mnemosyne ve Tethys. Her yönden tanrılara benzeyen Kyklop’ların ayırıcı özellikleri, alınlarında bir tek göz taşımalarıydı.",
    "Tepegöz diyebileceğimiz bu dev yaratıkların adları şöyleydi: Brontes (Gök gürültüsü), Steropes (Şimşek) ve Arges (Yıldırım). Hekatonkheir’lerin ise ellişer tane başı, yüzer tane kolu vardı. Bunlar da, Kottos, Briareus ve Gyes’di.",
    "Bu korkunç çocuklardan hem iğrenen hem kuşkulanan Uranos baba, onları doğar doğmaz toprağın derinliğine kapattı. Kahırlandı Gaia ve müthiş bir oyun düzenledi Uranos’a. Ak çelikten koca bir tırpan yapıp, kışkırttı oğullarını babalarına karşı. Böylesine bir öneri karşısında titredi hepsi korkudan. Yalnızca kurnaz Kronos, kötü bir babaya acımayacağını, bu işi kendisinin üstleneceğini söyledi.Sevindi Gaia. Pusuya yattı Kronos. Arzudan yanıp tutuşan Uranos, gelip kara geceyle boydan boya sarınca Toprak Ana’yı, uzattı sol elini pusuda bekleyen oğlu ve sağ elindeki keskin tırpanla kesip attı bir anda babasının hayalarını.Fışkıran kanlar saçıldı Toprak’a.",
    "Gebe kalan Toprak, yıllar sonra öç tanrıçaları Erinys’leri; parlak zırhlı, uzun kargılı Gigant’ları (Devler) ve bir de Orman Perileri’ni doğurdu.",
    "Tırpanın kestiği hayalar ise denize düştü ve kaldı enginde uzun zaman. Ak köpükler çıkıyordu tanrısal uzuvdan. Güzel Aphrodite türedi bu ak köpükten. Geçip Kythera’dan, Kıbrıs’ta karaya çıktı. Yürüdükçe yeşil çimenler fışkırıyordu narin ayaklarının altından. Böylece son buldu Uranos yönetimi.Kronos, çok kalabalık bir dünya üzerinde egemenlik sürdü. Nyks (Gece), Pontos (Deniz) ve Kronos’un kardeşleri Titanlar, sürüyle çocuk sahibi olmuşlardı.",
    "Nkys (Gece) Thanatos’u (ölüm), Hypnos’u (Uyku), Düşler’i, Okeanos Irmağı’nın ötesinde altın elmaların yetiştiği bahçeye bekçilik eden Hesperid’leri, kader tanrıçaları olan üç tane Moira’yı (Klotho, Lakhesis, Atropos), “İnsanlarda ölçüsüzlüğü, kendine ve talihine aşırı güveni cezalandıran” Nemesis’i, İhtiyarlık’ı, kavga tanrıçası Eris’i doğurdu.Annesi Gaia ile birleşen Pontos’dan deniz tanrıları ve tanrıçaları mey­dana geldi. Nereus, Thaumas ve Phorkys, Toprak Ana ile Deniz’in üç oğluydu. Keto ve Eurybie adında iki de kızları vardı.",
    "Nereus’la Titan Okeanos’un kızı Doris’in evlenmesinden elli kız doğdu. Bunlara Nereus Kızları denir. Thaumas’la Okeanos kızı Elektra’nın birleşme­sinden gökkuşağını simgeleyen hızlı İris ve kadın yüzlü, yaygın kanatlı, sivri pençeli, kapıp kaçan Harpyalar oluştu.",
    "Phorkys’le kardeşi Keto’nun birleşmesinden, doğdukları günden beri kocakarı olan Graia’larla Hesperidler Ülkesinde yaşayan Gorgo’lar (Sthenno, Euryale, Medusa) meydana geldi.",
    "Perseus tarafından başı vurulan Medusa’nın kanından Khrysaor’la kanatlı at Pegasos doğdu. Khrysaor, Okeanos kızı Kallirhoe ile evlendi. Bu evlilikten üç kafalı bir dev olan Geryoneus ve yarısı kadın, yarısı yılan, azman yaratık Ekhidna meydana geldi. Ayrıca Ekhidna’nın dev Typhon’la çiftleşmesinden bir sürü korkunç köpek ve canavar türedi: Hades’in köpeği Kerberos, bataklıklar canavan Hydra, ağzından ateş püskürten Khimaira vb. gibi.",
    "Kronos’un kardeşi Titanların çocuklarına gelince: Okeanos’la Titan kızkardeşi Tethys’den üç bin ırmak tanrısıyla, Okeanos Kızları denilen üç bin dişi varlık meydana geldi. Hyperion’la kızkardeşi Theia’nın evliliğin­den Helios (Güneş), Selene (Ay) ve Eos (Şafak) doğdu.Gaia ile Pontos’un kızı Eurybie’nin, Titan Krios’la birleşmesinden üç oğlan meydana geldi: Astraios, Pallas ve Perses. Astraios’un şafak tanrıçası Eos’la birleşmesinden rüzgârlar oluştu: Zephyros (Batı Rüzgârı, Karayel), Boreas (Poyraz), Notos (Lodos), Euros (Doğu Rüzgârı, Keşişleme).",
    "Rheia ise kardeşi Kronos’un yatağına girdi ve üçüncü tanrı kuşağı olan Olymposlular’ı doğurdu. Ne var ki korktu Kronos, oğullarından biri kral olup kendisini alaşağı edecek diye. Bunun için de Rheia’nın doğur­duğu her çocuğu yutmaya başladı. Hestia, Demeter, Hera, Hades ve Poseidon doğar doğmaz doğruca babalarının midesine gittiler. Buna çok üzülen Rheia, son çocuğu Zeus doğduğu zaman yaman bir kurnazlığa başvurdu: Kocasına, yeni doğan oğlu yerine, koca bir taşı beleyip verdi. Koios’la Phoibe’nin çiftleşmesinden Apollon ve Artemis’in anası Leto ile yıldızlı gece Asterie meydana geldi. Zeus büyüyünce, babası Kronos’a karşı eyleme geçti. Yuttuğu bütün çocukları birer birer kusturttu ona.",
    "İkiye ayrılmıştı Titanlar. Okeanos, Hyperion, Themis, Mnemosyne Zeus’un tarafını tuttular. Ötekiler ise Kronos’un. Tesalya’da Othrys’te yerleş­miş olan Titan tanrılarla, yine Tesalya’da Olympos’ta cephe kuran Kronos oğulları arasındaki savaş on yıl sürdü. Zeus, egemenliğini kabul ettirmek için her araca başvurdu. Ölüler Ülkesi’nin en derin yeri olan Tartaros’a inerek, orada tutsak tutulan Kykloplar’la Hekatonkheir’leri serbest bıraktı. Kykloplar Zeus’a gök gürlemesini, şimşek ve yıldırımı verdiler. Yüz Kolluların kapkara saldırılarıyla ezildi Titanlar.Toprağın altına tıkılıp, zincire vuruldular. Zeus’un buyruğuyla, üç tane Hekatonkheir (Yüz Kollu) bekçi konuldu başlarına.",
    "Kronos’u alt eden Zeus’un daha işi bitmemişti. Çocuklarının yenilgisine ve tutuklanmalarına öfkelenen Toprak Ana Gaia, Tartaros’la birleşerek, dev canavar Typhon’u doğurdu. Yüz tane yılan başı vardı Typhon’un. Her bir başından kara bir dil çıkıyordu ve gözleri ateş saçıyordu. Zeus toparladı gücünü, saldı canavarın üstüne bütün şimşeklerini ve yıldırımlarını; bir anda ateşe boğdu korkunç canavarın inanılmaz başlarını. Yıkıldı yere Typhon ve inim inim inledi Toprak.",
    "Zeus, Titanları ve Typhon’u yenerek Kronos’un en son umudunu da suya düşürdükten sonra, artık evrenin tek egemeni olarak, kardeşleri ara­sında yetki bölümü yaptı. Kendisi Gök’ü aldı. Kardeşi Poseidon’a Deniz’i, Hades’e de Yeraltı Ülkeleri’ni verdi. Yeryüzü ve özellikle Olympos, ortak mülkiyet sayıldı.",
    "Çok geçmeden Kronos oğullarına, Zeus’un çeşitli birleşmelerden sahip olduğu çocukları eklendi. Homeros, Zeus’un tek geçerli karısı olarak Hera’yı tanır. Oysa Hesiodos, Zeus’un birden çok evliliği bulunduğunu anlatır. Zeus’un ilk eşi, Okeanos kızı Metis’dir. Fakat Metis’den doğacak bir erkek çocuğun, babasını yenip onun yerine tahta geçeceğinin bildirilme­si üzerine Zeus, bilgeliği simgeleyen Metis’i, doğum yaptığı anda yutar.",
    "Zeus’un ikinci eşi, adaleti simgeleyen Themis’tir. Themis’ten Horalar (Eunomia/Disiplin, Dike/Adalet, Eirene/Barış) ve Moiralar doğar.Okeanos kızı Eurynome ile evlenmesinden Kharitler (Üç Güzeller) meydana gelir: Aglaie, Euphrosyne, Thalia.Dördüncü karısı Mnemosyne’den ise dokuz esin perisi Musalar doğar.",
    "Zeus’un asıl bundan sonraki evlilikleri Olympos kuşağının oluşmasını sağ­lar. Kardeşi Demeter’den, sonradan Hades’in karısı olacak olan Persephone doğar. Leto, Zeus’a Apollon ve Artemis’i verir.Hesiodos’un, “en son karısı” dediği Hera’dan, savaş tanrısı Ares, ateş tanrısı Hephaistos, gençlik tanrıçası Hebe ve doğumlara bakan ebe tanrıça Eileithyia doğar.",
    "Zeus kendi alnından Athena’yı yaratır. Atlas’ın kızı Maia’dan Hermes; Kadmos’la Harmonia’nın kızı Semele’den Dionysos doğar.Evrenin bu yeni egemenleri, Devler’in (Gigant’lar) saldırısına uğrarlar. Gaia, Uranos’un kesilen hayalanndan akan kandan gebe kalmış ve Devler’i doğurmuştu. Hesiodos, Tkeogonia’da, parlak zırhlı ve uzun kargı­lı Devler’i Gaia’nın doğurduğunu söyledikten sonra, bir daha söz etmez onlardan. Devler, Büyük İskender çağından itibaren, bedenleri birer yılan kuyruğuyla biten varlıklar olarak tasvir edilmişlerdir.",
    "Devler, dağları üst üste yığarak Olympos’a saldırırlar. Kehanete göre, onları yalnızca ölümlü bir insan yenebilecektir. Zeus, bu yüzden Herakles’e başvurur. Tanrılarla Devler Savaşı’na (Gigantomakhia) birçok tanrı katılır: Apollon, Ares, Artemis, Hekate, Hephaistos, Hermes, hatta Moiralar. Devlerden Enkelados kaçarken, Athena, üstüne Sicilya adasını fırlatır. Bir başka dev olan Pallas’ın ise derisini yüzüp savaşta zırh olarak kullanır. Kısaca, Titanların başına gelen, Devlerin de başına gelir."
  ];

  List Romen = [
    "Geleneklere göre 21 Nisan 753 gününde Romulus ve ikiz erkek kardeşi Remus, yetim bebekler iken bir dişi kurt tarafından emzirildikleri yerde Roma şehrini kurdu. Aslında Romulus ve Remus efsanesi, MÖ 4. yüzyılda bir zamanda ortaya çıkmıştı. Roma’nın tam kuruluş günü ise Romalı bilgin Marcus Terentius Varro tarafından MÖ 1. yüzyılda kesinleştirilmişti.",
    "Efsaneye göre Romulus ve Remus, Alba Longa’nın Kralı Numitor’ın kızı Silvia Rhea’nın oğullarıydı. Alba Longa, sonradan Roma olacak bölgenin güneydoğusundaki Alba Tepeleri’nde bulunan efsanevi bir şehirdi. İkizlerin doğumundan önce, Numitor’un küçük kardeşi Amulius onu tahttan indirdi, ve Numitor’ın kızı Rhea’yı da, tahta rakip adaylar doğurmaması için bir rahibe olmaya zorladı. Fakat Rhea daha önceden Savaş tanrısı Mars’tan hamile kalmıştı ve Romus ve Remulus’u doğurdu. Amulius iki kardeşin Tiber nehrinde boğdurulmalarını emretti. Fakat çocuklar kurtuldu ve Palatine tepesinin eteklerinde kıyıya vurdu. Burada da çoban Faustulus tarafından bulunana kadar bir dişi kurt tarafından emzirildiler ve bakıldılar.",
    "Faustulus ve eşi tarafından büyütülen ikizler daha sonra genç bir çoban savaşçılar grubunun lideri oldular. Gerçek kimliklerini öğrendikten sonra kardeşler Alba Longa’ya saldırdı, hain Amulius’u öldürdü ve dedelerini tekrar tahta çıkardı. İkizle daha sonra, çocukken kurtarıldıkları yerde bir şehir kurmaya karar verdi. Fakat kısa zaman içinde önemsiz bir tartışmaya girdiler, ve Remus kardeşi tarafından öldürüldü. Romulus da kurdukları yerleşimin lideri oldu ve şehir onun ardından “Roma” ismini aldı.",
    "Bu yeni şehrin iskan edilmesi için Romulus kaçaklara ve sürgün edilmiş insanlara sığınak sundu. Fakat Roma’da kadın yoktu. Bu yüzden Romulus komşu Sabine’leri bir festivale davet ettikten sonra kadınlarını kaçırdı. Daha sonra bir savaş çıktı, fakat Sabine kadınları, Sabine erkeklerinin Roma’yı ele geçirmesini engelledi. Bir barış antlaşması yapıldı ve iki topluluk Romulus’un ve Sabine kralı Titus Tatius’un hakimiyeti altında birleşti. Fakat, belki de Romulus’un neden olduğu, Tatius’un erken ölümü, Romalı’nın yine tek kral olmasını sağladı.",
  ];

  String getinfo(int num) {
    return Norse[num];
  }

  String greekinfo(int num) {
    return Greek[num];
  }

  String romeninfo(int num) {
    return Romen[num];
  }
}
